spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://127.0.0.2:3309/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: false
  jackson:
#    default-property-inclusion: non_null

server:
  context-path: /sell
  port: 8088